# docker-compose.yml
name: ${PROJECT_NAME}
version: '3.1'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
       - ./.volume:/var/lib/postgresql/data
    ports:
      - "${HOST_PORT}:5432"